
package exemplloretangulo.newpackage;

/**
 *
 * @author aluno
 */
public class funcionarioobj {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
       // criando objeto
       Funcionario f = new Funcionario();
       
       f.setNome("Luis");
       f.setSobrenome("Silva");
       f.setHorastrabalhadas(10);
       f.setHvalorPorHora(25.50);
       // parado em chame o metodo nomeCompleto
    }
    
}
